### PR TITLE
Align balances on decimal point

### LINKED ISSUE #193: Align balances on decimal point
## Is your feature request related to a problem? Please describe.
Screenshot_20240328_190349

## Describe the solution you'd like
Notes_240328_190628

### PR DESCRIPTION
**Pull request by mike-petrov**
closes #193

Signed-off-by: Mikhail Petrov <mike@nspcc.ru>

### CODE REVIEW

**Comment by roman-khimov** [comment]
Screen?

**Comment by mike-petrov** [comment]
image

**Comment by roman-khimov** [comment]
Don't seem to be aligned.

**Comment by roman-khimov** [comment]
Invisible zeroes can't solve it, but you can break this thing into 2/3 parts: decimal aligned to the right, dot (at the same level, if present) and fractional aligned to the left (if present).

**Comment by mike-petrov** [comment]
Screenshot 2024-08-29 at 18 50 32
Screenshot 2024-08-29 at 18 50 24

**Review by roman-khimov — APPROVED** [review]

**Pull request merged**
